defmodule ShotDs.Util.Lexer do
  @moduledoc """
  Contains a `tokenize/1` function for tokenizing a string representing a
  formula in THF syntax or a TPTP TH0/TH1 problem file using `NimbleParsec`.
  This is mainly used as a preprocessing step for parsing. For information about
  the returned structure, see
  https://hexdocs.pm/nimble_parsec/NimbleParsec.html.

  Every token is a 3-tuple `{type, value, byte_offset}` where `byte_offset` is
  the position of the first byte of the token in the original input string.
  Downstream parsers use this to report the position of type errors.

  The token layer follows the lexical rules of the TPTP syntax BNF
  (https://tptp.org/UserDocs/TPTPLanguage/SyntaxBNF.html):

  | BNF rule                                | token type                         |
  | --------------------------------------- | ---------------------------------- |
  | `<lower_word>`                          | `:atom` (or `:keyword`)            |
  | `<upper_word>`                          | `:var`                             |
  | `<single_quoted>`                       | `:distinct` (an `<atomic_word>`)   |
  | `<distinct_object>` (`"…"`)             | `:distinct_object`                 |
  | `<dollar_word>`, `<dollar_dollar_word>` | `:system`                          |
  | `<integer>`, `<rational>`, `<real>`     | `:integer`, `:rational`, `:real`   |
  | `<comment_line>`, `<comment_block>`     | ignored                            |

  Escape sequences (`\\'`, `\\"`, `\\\\`) inside quoted tokens are resolved, and
  the surrounding quotes are stripped from the token value.
  """

  import NimbleParsec

  @typedoc """
  Tokens are generated by the lexer as a list of `{type, value, byte_offset}`
  triples, where `type` is a label given as atom, `value` is the original
  string representation of the token, and `byte_offset` is the position in
  the original input.
  """
  @type tokens() :: [{atom(), String.t() | atom(), non_neg_integer()}]

  whitespace = ascii_string([?\s, ?\t, ?\n, ?\r], min: 1) |> ignore()

  comment_line = string("%") |> concat(ascii_string([not: ?\n], min: 0)) |> ignore()

  comment_block =
    string("/*")
    |> repeat(lookahead_not(string("*/")) |> utf8_char([]))
    |> string("*/")
    |> ignore()

  @keywords %{
    "include" => :include,
    "thf" => :thf
  }

  @doc false
  def categorize_atom(name) do
    case Map.fetch(@keywords, name) do
      {:ok, keyword} -> {:keyword, keyword}
      :error -> {:atom, name}
    end
  end

  @doc false
  def attach_offset(rest, [{type, value}], context, _line, end_offset) do
    start = end_offset - byte_size(to_string(value))
    {rest, [{type, value, start}], context}
  end

  # Quoted tokens carry their raw byte length (quotes and escapes included) so
  # that the reported offset stays exact even though the token value is the
  # unescaped content.
  @doc false
  def attach_raw_offset(rest, [{type, value, raw_length}], context, _line, end_offset) do
    {rest, [{type, value, end_offset - raw_length}], context}
  end

  @doc false
  def build_quoted(parts, type) do
    raw = Enum.join(parts)
    value = raw |> binary_part(1, byte_size(raw) - 2) |> unescape()
    {type, value, byte_size(raw)}
  end

  defp unescape(str), do: Regex.replace(~r/\\(.)/, str, "\\1")

  sign = ascii_string([?+, ?-], 1)
  digits = ascii_string([?0..?9], min: 1)
  exponent = ascii_string([?e, ?E], 1) |> optional(sign) |> concat(digits)

  real_number =
    optional(sign)
    |> choice([
      digits |> string(".") |> concat(digits) |> optional(exponent),
      digits |> concat(exponent)
    ])
    |> reduce({Enum, :join, []})
    |> unwrap_and_tag(:real)
    |> post_traverse({__MODULE__, :attach_offset, []})

  rational_number =
    optional(sign)
    |> concat(digits)
    |> string("/")
    |> concat(digits)
    |> reduce({Enum, :join, []})
    |> unwrap_and_tag(:rational)
    |> post_traverse({__MODULE__, :attach_offset, []})

  integer_number =
    optional(sign)
    |> concat(digits)
    |> reduce({Enum, :join, []})
    |> unwrap_and_tag(:integer)
    |> post_traverse({__MODULE__, :attach_offset, []})

  number = choice([real_number, rational_number, integer_number])

  # `<dollar_word>` and `<dollar_dollar_word>` share the `:system` token type.
  system_symbol =
    string("$")
    |> optional(string("$"))
    |> concat(ascii_string([?a..?z, ?A..?Z, ?0..?9, ?_], min: 1))
    |> reduce({Enum, :join, []})
    |> unwrap_and_tag(:system)
    |> post_traverse({__MODULE__, :attach_offset, []})

  variable =
    ascii_string([?A..?Z], 1)
    |> optional(ascii_string([?a..?z, ?A..?Z, ?0..?9, ?_], min: 1))
    |> reduce({Enum, :join, []})
    |> unwrap_and_tag(:var)
    |> post_traverse({__MODULE__, :attach_offset, []})

  atom_ident =
    ascii_string([?a..?z], 1)
    |> optional(ascii_string([?a..?z, ?A..?Z, ?0..?9, ?_], min: 1))
    |> reduce({Enum, :join, []})
    |> map({__MODULE__, :categorize_atom, []})
    |> post_traverse({__MODULE__, :attach_offset, []})

  quoted_content = fn quote_char ->
    repeat(
      choice([
        string("\\") |> utf8_string([], 1),
        utf8_string([not: quote_char, not: ?\\], 1)
      ])
    )
  end

  single_quoted =
    string("'")
    |> concat(quoted_content.(?'))
    |> string("'")
    |> reduce({__MODULE__, :build_quoted, [:distinct]})
    |> post_traverse({__MODULE__, :attach_raw_offset, []})

  distinct_object =
    string("\"")
    |> concat(quoted_content.(?"))
    |> string("\"")
    |> reduce({__MODULE__, :build_quoted, [:distinct_object]})
    |> post_traverse({__MODULE__, :attach_raw_offset, []})

  symbols =
    choice([
      # Sequents, definitions and let-bindings
      string("-->") |> replace({:gentzen_arrow, "-->"}),
      string("-") |> replace({:minus, "-"}),
      string(":=") |> replace({:assignment, ":="}),
      string("==") |> replace({:identical, "=="}),
      string("<<") |> replace({:subtype, "<<"}),

      # Connectives
      string("<=>") |> replace({:equiv, "<=>"}),
      string("=>") |> replace({:implies, "=>"}),
      string("<=") |> replace({:implied_by, "<="}),
      string("<~>") |> replace({:xor, "<~>"}),
      string("~|") |> replace({:nor, "~|"}),
      string("~&") |> replace({:nand, "~&"}),

      # Quantifiers and Operators
      string("!!") |> replace({:forall, "!!"}),
      string("!=") |> replace({:neq, "!="}),
      string("!>") |> replace({:forall_type, "!>"}),
      string("!") |> replace({:forall, "!"}),
      string("?*") |> replace({:exists_type, "?*"}),
      string("??") |> replace({:exists, "??"}),
      string("?") |> replace({:exists, "?"}),
      string("^") |> replace({:lambda, "^"}),
      string("@@+") |> replace({:choice_const, "@@+"}),
      string("@@-") |> replace({:description_const, "@@-"}),
      string("@+") |> replace({:choice, "@+"}),
      string("@-") |> replace({:description, "@-"}),
      string("@=") |> replace({:eq, "@="}),
      string("@") |> replace({:app, "@"}),
      string("~") |> replace({:not, "~"}),
      string("|") |> replace({:or, "|"}),
      string("&") |> replace({:and, "&"}),
      string("=") |> replace({:eq, "="}),

      # Punctuation
      string("(") |> replace({:lparen, "("}),
      string(")") |> replace({:rparen, ")"}),
      string("[") |> replace({:lbracket, "["}),
      string("]") |> replace({:rbracket, "]"}),
      string(":") |> replace({:colon, ":"}),
      string(",") |> replace({:comma, ","}),
      string(".") |> replace({:dot, "."}),

      # Types
      string(">") |> replace({:arrow, ">"}),
      string("*") |> replace({:star, "*"}),
      string("+") |> replace({:plus, "+"})
    ])
    |> post_traverse({__MODULE__, :attach_offset, []})

  defparsec(
    :tokenize,
    repeat(
      choice([
        whitespace,
        comment_line,
        comment_block,
        number,
        symbols,
        system_symbol,
        variable,
        atom_ident,
        single_quoted,
        distinct_object
      ])
    )
  )

  @doc """
  Converts a byte offset into the source string into a `{line, column}` pair
  (1-indexed). Used for decorating type-error messages produced by the parser.
  """
  @spec byte_offset_to_line_col(String.t(), non_neg_integer()) ::
          {pos_integer(), pos_integer()}
  def byte_offset_to_line_col(source, target_offset) do
    prefix = binary_part(source, 0, min(target_offset, byte_size(source)))
    lines = String.split(prefix, "\n")
    line = length(lines)
    last_line = List.last(lines, "")
    {line, String.length(last_line) + 1}
  end
end
